[package]
name = "binaural-beat-generator-cli"
version = "0.1.0"
edition = "2024"
authors = ["Chris Horton"]

[dependencies]
anyhow = "1.0.98"
colored = "3.0.0"
cpal = "0.16.0"
crossterm = "0.29.0"
inquire = "0.7.5"

